require './md_file'

desc "Inspect a md file"
task :toc, :which do |t, args|
  puts MdFile.new(Path.dir/args[:which]).toc.to_yaml
end

desc "Run rspec tests"
task :test do
  system("rspec --color -I. spec/*.rb")
end
task :default => :test
